version: '3.8'

services:
  web:
    build: .
    command: gunicorn multilang_site.wsgi:application --bind 0.0.0.0:8000
    ports:
      - "8000:8000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    volumes:
      - .:/app
