# Generated by Django 5.0.6 on 2024-06-27 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_embedding'),
    ]

    operations = [
        migrations.CreateModel(
            name='VectorStore',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('data', models.BinaryField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Embedding',
        ),
    ]
