# Generated by Django 5.0.6 on 2024-06-27 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_vectorstore_delete_embedding'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vectorstore',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='vectorstore',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
