# Generated by Django 5.0.6 on 2024-06-27 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_vectorstore_created_at_alter_vectorstore_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vectorstore',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
