# Generated by Django 5.0.6 on 2024-06-27 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_vectorstore_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vectorstore',
            name='data',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='vectorstore',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
