# Generated by Django 5.0.6 on 2024-06-27 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_vectorstore_data_alter_vectorstore_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vectorstore',
            name='data',
            field=models.BinaryField(),
        ),
        migrations.AlterField(
            model_name='vectorstore',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
