# Generated by Django 5.0.6 on 2024-06-27 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_vectorstore_updated_at'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VectorStore',
        ),
    ]
